name: 'mehrdad_dbt_databricks'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# تنظیمات سراسری برای سازگاری با دیتابریکس غیر-یونیتی کاتالوگ
config:
  send_anonymous_usage_stats: false

models:
  mehrdad_dbt_databricks:
    # مشخص کردن مت‌استور پیش‌فرض برای جلوگیری از خطای Unity Catalog
    +catalog: hive_metastore
    
    staging:
      +materialized: view
      +schema: default
      
    vault:
      +materialized: incremental
      +schema: default