version: 2

sources:
  - name: default
    database: default   # یا نام کاتالوگ/دیتابیس شما در دیتابریکس
    schema: default     # نام اسکیما که جدول برنز در آن قرار دارد
    tables:
      - name: TaxiData_Bronze